# Generated by Django 6.0.6 on 2026-07-28 02:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_household_calendar_default_view_and_more'),
        ('solace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='source_node',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bill',
            name='source_record_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='source_record_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('source_node', ''), _negated=True), models.Q(('source_record_type', ''), _negated=True), ('source_record_id__isnull', False)), fields=('household', 'source_node', 'source_record_type', 'source_record_id'), name='unique_active_solace_source_bill'),
        ),
    ]
