# Generated by Django 6.0.6 on 2026-07-29 08:52

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


DEFAULT_CATEGORIES = (
    ("mortgage", "bill"),
    ("utilities", "bill"),
    ("insurance", "bill"),
    ("council", "bill"),
    ("debt", "bill"),
    ("subscription", "bill"),
    ("childcare", "bill"),
    ("travel", "purchase"),
    ("christmas", "purchase"),
    ("home", "purchase"),
    ("other", "both"),
)


def seed_default_categories(apps, schema_editor):
    Household = apps.get_model("core", "Household")
    FinanceCategory = apps.get_model("solace", "FinanceCategory")
    for household in Household.objects.all():
        for position, (name, category_type) in enumerate(DEFAULT_CATEGORIES, start=1):
            FinanceCategory.objects.get_or_create(
                household=household,
                name=name,
                defaults={"category_type": category_type, "position": position * 10},
            )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_household_calendar_default_view_and_more"),
        ("solace", "0004_bill_occurrences"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="category",
            field=models.CharField(default="other", max_length=100),
        ),
        migrations.CreateModel(
            name="AccountBalanceSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("snapshot_date", models.DateField(default=django.utils.timezone.localdate)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notes", models.TextField(blank=True, default="")),
                ("visibility", models.CharField(choices=[("private", "Private"), ("household", "Household"), ("role_restricted", "Role Restricted"), ("sensitive", "Sensitive")], default="sensitive", max_length=20)),
                ("sensitivity", models.CharField(choices=[("normal", "Normal"), ("financial", "Financial"), ("health", "Health"), ("document", "Document"), ("private", "Private")], default="financial", max_length=20)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("household", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.household")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-snapshot_date", "-id"]},
        ),
        migrations.CreateModel(
            name="CycleCloseout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("cycle_start", models.DateField()),
                ("cycle_end", models.DateField()),
                ("status", models.CharField(choices=[("open", "Open"), ("closed", "Closed")], default="open", max_length=20)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("visibility", models.CharField(choices=[("private", "Private"), ("household", "Household"), ("role_restricted", "Role Restricted"), ("sensitive", "Sensitive")], default="sensitive", max_length=20)),
                ("sensitivity", models.CharField(choices=[("normal", "Normal"), ("financial", "Financial"), ("health", "Health"), ("document", "Document"), ("private", "Private")], default="financial", max_length=20)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("household", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.household")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-cycle_start"],
                "constraints": [models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("household", "cycle_start"), name="unique_active_solace_cycle_closeout")],
            },
        ),
        migrations.CreateModel(
            name="FinanceCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("category_type", models.CharField(choices=[("bill", "Bill"), ("purchase", "Purchase"), ("both", "Both")], default="both", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("visibility", models.CharField(choices=[("private", "Private"), ("household", "Household"), ("role_restricted", "Role Restricted"), ("sensitive", "Sensitive")], default="sensitive", max_length=20)),
                ("sensitivity", models.CharField(choices=[("normal", "Normal"), ("financial", "Financial"), ("health", "Health"), ("document", "Document"), ("private", "Private")], default="financial", max_length=20)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("household", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.household")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["position", "name"],
                "constraints": [models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("household", "name"), name="unique_active_solace_category_name")],
            },
        ),
        migrations.CreateModel(
            name="PaydayChecklistPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("source_key", models.CharField(max_length=120)),
                ("label", models.CharField(max_length=200)),
                ("is_hidden", models.BooleanField(default=False)),
                ("reason", models.CharField(blank=True, default="", max_length=200)),
                ("visibility", models.CharField(choices=[("private", "Private"), ("household", "Household"), ("role_restricted", "Role Restricted"), ("sensitive", "Sensitive")], default="sensitive", max_length=20)),
                ("sensitivity", models.CharField(choices=[("normal", "Normal"), ("financial", "Financial"), ("health", "Health"), ("document", "Document"), ("private", "Private")], default="financial", max_length=20)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("household", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.household")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["label"],
                "constraints": [models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("household", "source_key"), name="unique_active_solace_checklist_preference")],
            },
        ),
        migrations.CreateModel(
            name="SolaceSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("currency_symbol", models.CharField(default="$", max_length=8)),
                ("budget_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("default_buffer_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("payday_bill_handling", models.CharField(choices=[("new_cycle", "New pay cycle"), ("previous_cycle", "Previous pay cycle")], default="new_cycle", max_length=20)),
                ("show_help_tips", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("household", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.household")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name_plural": "Solace settings",
                "constraints": [models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("household",), name="unique_active_solace_settings")],
            },
        ),
        migrations.RunPython(seed_default_categories, migrations.RunPython.noop),
    ]
