# Generated by Django 6.0.6 on 2026-07-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solace", "0005_alter_bill_category_accountbalancesnapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solacesettings",
            name="cycle_anchor_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solacesettings",
            name="dashboard_reminders",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="solacesettings",
            name="due_soon_days",
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
