# Generated by Django 5.0.6 on 2026-08-10 01:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_household_calendar_default_view_and_more'),
        ('solace', '0007_bill_end_date_bill_is_autopay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetbucket',
            name='purpose',
            field=models.CharField(choices=[('bills', 'Bills'), ('savings', 'Savings'), ('spending', 'Spending'), ('purchases', 'Planned purchases'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='BucketEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('deposit', 'Money in'), ('withdrawal', 'Money out'), ('adjustment', 'Correction')], default='deposit', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('occurred_at', models.DateTimeField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('household', 'Household'), ('role_restricted', 'Role Restricted'), ('sensitive', 'Sensitive')], default='sensitive', max_length=20)),
                ('sensitivity', models.CharField(choices=[('normal', 'Normal'), ('financial', 'Financial'), ('health', 'Health'), ('document', 'Document'), ('private', 'Private')], default='financial', max_length=20)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='solace.budgetbucket')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bucket entry',
                'verbose_name_plural': 'bucket entries',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
    ]
