# Generated by Django 5.0.6 on 2026-08-10 01:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_household_calendar_default_view_and_more'),
        ('solace', '0008_bucket_entries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payday',
            name='allocation_mode',
            field=models.CharField(choices=[('standard', 'Through the usual bucket rules'), ('lump', 'All of it into one bucket'), ('custom', 'Split across chosen buckets')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='payday',
            name='income_scope',
            field=models.CharField(choices=[('individual', "One person's income"), ('shared', 'Shared household income')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='payday',
            name='lump_bucket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='solace.budgetbucket'),
        ),
        migrations.AddField(
            model_name='payday',
            name='owner_name',
            field=models.CharField(blank=True, default='Household', max_length=120),
        ),
        migrations.CreateModel(
            name='IncomeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('is_remainder', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('household', 'Household'), ('role_restricted', 'Role Restricted'), ('sensitive', 'Sensitive')], default='sensitive', max_length=20)),
                ('sensitivity', models.CharField(choices=[('normal', 'Normal'), ('financial', 'Financial'), ('health', 'Health'), ('document', 'Document'), ('private', 'Private')], default='financial', max_length=20)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='solace.budgetbucket')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('payday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='solace.payday')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'income allocation',
                'ordering': ['position', 'id'],
            },
        ),
    ]
