# Generated by Django 5.0.6 on 2026-06-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meridian', '0002_enable_meridian_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='meridianpointsentry',
            name='transaction_type',
            field=models.CharField(choices=[('task_approved', 'Task approved'), ('routine_completed', 'Routine completed'), ('allowance', 'Allowance'), ('manual_adjustment', 'Manual adjustment'), ('reward_requested', 'Reward requested (reserved)'), ('reward_refunded', 'Reward refunded'), ('reward_cancelled_refund', 'Reward cancelled (refund)'), ('group_goal_contribution', 'Group goal contribution'), ('group_goal_refund', 'Group goal refund'), ('wishlist_contribution', 'Wishlist contribution'), ('wishlist_refund', 'Wishlist refund')], db_index=True, default='manual_adjustment', max_length=40),
        ),
    ]
