# Generated by Django 5.0.6 on 2026-06-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meridian', '0003_meridianpointsentry_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meridiantask',
            name='availability_window',
            field=models.CharField(blank=True, default='always', max_length=30),
        ),
        migrations.AddField(
            model_name='meridiantask',
            name='completion_behavior',
            field=models.CharField(choices=[('stay_active', 'Stay active (repeatable)'), ('hide_after_approval', 'Hide after approval (one-off)')], default='stay_active', max_length=30),
        ),
        migrations.AddField(
            model_name='meridiantask',
            name='completion_scope',
            field=models.CharField(choices=[('per_person', 'Each person separately'), ('household', 'Household (first to complete)')], default='per_person', max_length=20),
        ),
        migrations.AddField(
            model_name='meridiantask',
            name='hot_bonus_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meridiantask',
            name='hot_label',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='meridiantask',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meridiantask',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
