# Generated by Django 5.0.6 on 2026-06-25 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_household'),
        ('meridian', '0004_meridiantask_availability_window_and_more'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeridianRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('points', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('household', 'Household'), ('role_restricted', 'Role Restricted'), ('sensitive', 'Sensitive')], default='household', max_length=20)),
                ('assigned_to_person', models.ForeignKey(blank=True, help_text='If set, only this person sees/completes the routine; null = everyone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_meridian_routines', to='people.person')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'meridian routine',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='meridianpointsentry',
            name='source_routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_entries', to='meridian.meridianroutine'),
        ),
        migrations.CreateModel(
            name='MeridianRoutineCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateField(db_index=True)),
                ('voided', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meridian_routine_completions', to='people.person')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='meridian.meridianroutine')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'meridian routine completion',
                'ordering': ['-completed_date', '-id'],
            },
        ),
    ]
