# Generated by Django 5.0.6 on 2026-06-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meridian', '0005_meridianroutine_meridianpointsentry_source_routine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meridianreward',
            name='allow_multiple_in_cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meridianreward',
            name='daily_limit_per_user',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meridianreward',
            name='disappear_when_empty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meridianreward',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='meridianreward',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meridianreward',
            name='price_estimate',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='meridianreward',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meridianreward',
            name='store_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
