# Generated by Django 5.0.6 on 2026-06-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meridian', '0009_meridianallowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='meridiancategory',
            name='kind',
            field=models.CharField(choices=[('task', 'Task'), ('reward', 'Reward')], db_index=True, default='task', max_length=10),
        ),
    ]
