# Generated by Django 5.0.6 on 2026-07-10 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meridian', '0011_meridiantaskcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='meridianreward',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='meridian.meridiancategory'),
        ),
    ]
