# Generated by Django 5.0.6 on 2026-08-18 08:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_household_location_db_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLaunchShortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('target_key', models.CharField(max_length=64)),
                ('target_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('custom_label', models.CharField(blank=True, default='', max_length=60)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('launch_mode', models.CharField(choices=[('normal', 'Normal'), ('focused', 'Focused')], default='normal', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_launch_shortcuts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'quick launch shortcut',
                'verbose_name_plural': 'quick launch shortcuts',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='quicklaunchshortcut',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'target_key', 'target_object_id'), name='quicklaunch_unique_active_shortcut'),
        ),
    ]
