# Generated by Django 5.0.6 on 2026-08-12 09:03

from django.db import migrations, models

# Importing the live helper rather than freezing a copy: device_naming holds a pure, stable
# naming heuristic with no model/schema dependency, so there is nothing here for a later schema
# change to invalidate.
from apps.notifications.device_naming import describe

# The labels the old frontend heuristic could produce. Devices still carrying one of these were
# never really named by their owner, so backfilling regenerates them instead of preserving a
# useless "This device". Anything else was typed by a human and is kept as a custom label.
_GENERATED_LEGACY_LABELS = {
    "", "This device", "Android device", "iPhone", "iPad", "Mac", "Windows PC",
}


def backfill_device_naming(apps, schema_editor):
    PushDevice = apps.get_model("notifications", "PushDevice")
    for device in PushDevice.objects.all():
        browser, platform, generated = describe(device.user_agent)
        device.browser = browser
        device.platform = platform
        if device.label in _GENERATED_LEGACY_LABELS:
            device.label = generated
        else:
            device.label_is_custom = True
        device.save(update_fields=["browser", "platform", "label", "label_is_custom"])


def unbackfill(apps, schema_editor):
    """No-op: the columns this filled are dropped by the reverse AddField operations."""


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationreminderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushdevice',
            name='browser',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='label_is_custom',
            field=models.BooleanField(default=False, help_text='The owner renamed this device; do not regenerate its label.'),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.RunPython(backfill_device_naming, unbackfill),
    ]
