# Generated by Django 5.0.6 on 2026-09-22 02:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_household_location_db_defaults'),
        ('notifications', '0005_pushdevice_browser_pushdevice_label_is_custom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='source_record_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='source_record_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['source_record_type', 'source_record_id', 'is_read'], name='notif_source_record_idx'),
        ),
    ]
