# Generated by Django 6.0.6 on 2026-06-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlaslistitem',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atlaslistitem',
            name='quantity',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
