# Generated by Django 6.0.6 on 2026-07-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0002_atlaslistitem_due_at_atlaslistitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlasreminder',
            name='is_all_day',
            field=models.BooleanField(default=False),
        ),
    ]
