# Generated by Django 5.0.6 on 2026-08-11 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0004_multi_person_assignment'),
        ('attachments', '0001_initial'),
        ('core', '0004_household_calendar_default_view_and_more'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atlaslist',
            name='owner_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_atlas_lists', to='people.person'),
        ),
        migrations.AddField(
            model_name='atlaslistitem',
            name='currency',
            field=models.CharField(blank=True, default='AUD', max_length=3),
        ),
        migrations.AddField(
            model_name='atlaslistitem',
            name='image_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atlas_product_items', to='attachments.attachment'),
        ),
        migrations.AddField(
            model_name='atlaslistitem',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atlaslistitem',
            name='product_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='atlaslistitem',
            name='retailer',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='atlaslistitem',
            name='source_image_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='atlaslistitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='atlaslist',
            name='list_type',
            field=models.CharField(choices=[('todo', 'To Do'), ('grocery', 'Grocery'), ('checklist', 'Checklist'), ('shopping', 'Shopping'), ('wishlist', 'Wish list'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='AtlasListSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('product_url', models.CharField(blank=True, default='', max_length=1000)),
                ('source_image_url', models.CharField(blank=True, default='', max_length=1000)),
                ('retailer', models.CharField(blank=True, default='', max_length=160)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, default='AUD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], default='pending', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_suggestion', to='atlas.atlaslistitem')),
                ('atlas_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='atlas.atlaslist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('suggested_by_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atlas_list_suggestions', to='people.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
