# Generated by Django 5.0.6 on 2026-08-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0006_atlaslistitem_calendar_event_id_atlascontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlaslistitem',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='', max_length=10),
        ),
    ]
