# Generated by Django 5.0.6 on 2026-08-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0008_reminder_recipients_and_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlaslistitem',
            name='is_all_day',
            field=models.BooleanField(default=True, help_text='A To-do with a due date but no specific time is all-day by default.'),
        ),
        migrations.AddField(
            model_name='atlaslistitem',
            name='is_important',
            field=models.BooleanField(default=False, help_text='Simple ★ Important flag for To-dos — deliberately not High/Medium/Low priority.'),
        ),
        migrations.AddField(
            model_name='atlaslistitem',
            name='notify_offsets',
            field=models.JSONField(blank=True, default=list, help_text='Minutes before due_at to notify (0 = at time), e.g. [0, 60, 1440] for at-time + 1 hour before + 1 day before. Empty means no notifications.'),
        ),
    ]
