# Generated by Django 6.0.6 on 2026-07-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_household'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='family_colour',
            field=models.CharField(blank=True, default='#7C6F5A', max_length=20),
        ),
    ]
