# Generated by Django 6.0.6 on 2026-07-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_household_family_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='calendar_default_view',
            field=models.CharField(choices=[('month', 'Month'), ('week', 'Week'), ('day', 'Day'), ('agenda', 'Agenda')], default='month', max_length=10),
        ),
        migrations.AddField(
            model_name='household',
            name='calendar_time_format',
            field=models.CharField(choices=[('12h', '12-hour'), ('24h', '24-hour')], default='12h', max_length=3),
        ),
        migrations.AddField(
            model_name='household',
            name='calendar_week_start',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday')], default=1),
        ),
    ]
