# Generated by Django 5.0.6 on 2026-08-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_household_calendar_default_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='household',
            name='locality',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='household',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='household',
            name='region',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
