# Generated by Django 5.0.6 on 2026-08-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_calendar_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='country',
            field=models.CharField(blank=True, db_default='', default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='household',
            name='locality',
            field=models.CharField(blank=True, db_default='', default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='household',
            name='postcode',
            field=models.CharField(blank=True, db_default='', default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='household',
            name='region',
            field=models.CharField(blank=True, db_default='', default='', max_length=16),
        ),
    ]
