# Generated by Django 5.0.6 on 2026-08-11 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_household_calendar_default_view_and_more'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source_node', models.CharField(max_length=40)),
                ('source_record_type', models.CharField(max_length=80)),
                ('source_record_id', models.PositiveBigIntegerField()),
                ('url', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=255)),
                ('retailer', models.CharField(blank=True, default='', max_length=160)),
                ('currency', models.CharField(default='AUD', max_length=3)),
                ('baseline_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lowest_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rule', models.CharField(choices=[('meaningful_drop', 'Meaningful price drop'), ('explicit_sale', 'Marked on sale'), ('target', 'At or below target')], default='meaningful_drop', max_length=24)),
                ('threshold_percent', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('last_notified_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('owner_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_watches', to='people.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('observed_at', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_sale', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='link_imports.linkwatch')),
            ],
            options={
                'ordering': ['-observed_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='linkwatch',
            constraint=models.UniqueConstraint(fields=('household', 'source_node', 'source_record_type', 'source_record_id', 'owner_person'), name='link_imports_unique_watch_source_owner'),
        ),
    ]
