from django.urls import path

from apps.solace.views import (
    AccountBalanceDetailView,
    AccountBalanceListView,
    BalanceForecastView,
    BillDetailView,
    BillListView,
    BillOccurrenceActionView,
    BillOccurrenceTimelineView,
    BillImportCancelView,
    BillImportConfirmView,
    BillImportPreviewView,
    BillPaidView,
    BucketDetailView,
    BucketListView,
    CategoryReportView,
    ChecklistDetailView,
    ChecklistListView,
    ChecklistPreferenceView,
    CycleCloseoutView,
    FinanceCategoryDetailView,
    FinanceCategoryListView,
    PayCycleChecklistView,
    PayCyclePlanView,
    PaydayDetailView,
    PaydayListView,
    PurchaseDetailView,
    PurchaseListView,
    PurchaseSavingsView,
    SolaceHealthView,
    SolaceBootstrapView,
    SolaceSearchView,
    SolaceScheduleView,
    SolaceSettingsView,
    SolaceCsvExportView,
    SolaceXlsxExportView,
    SubscriptionDetailView,
    SubscriptionListView,
)

urlpatterns = [
    path("bootstrap/", SolaceBootstrapView.as_view(), name="solace-bootstrap"),
    path("export/<str:export_type>.csv", SolaceCsvExportView.as_view(), name="solace-csv-export"),
    path("export/backup.xlsx", SolaceXlsxExportView.as_view(), name="solace-xlsx-export"),
    path("import/bills/preview/", BillImportPreviewView.as_view(), name="solace-bill-import-preview"),
    path("import/bills/confirm/", BillImportConfirmView.as_view(), name="solace-bill-import-confirm"),
    path("import/bills/cancel/", BillImportCancelView.as_view(), name="solace-bill-import-cancel"),
    path("search/", SolaceSearchView.as_view(), name="solace-search"),
    path("settings/", SolaceSettingsView.as_view(), name="solace-settings"),
    path("health/", SolaceHealthView.as_view(), name="solace-health"),
    path("reports/categories/", CategoryReportView.as_view(), name="solace-category-report"),
    path("forecast/", BalanceForecastView.as_view(), name="solace-forecast"),
    path("closeout/", CycleCloseoutView.as_view(), name="solace-closeout"),
    path("schedule/", SolaceScheduleView.as_view(), name="solace-schedule"),
    path(
        "occurrences/<int:occurrence_id>/<str:action>/",
        BillOccurrenceActionView.as_view(),
        name="solace-occurrence-action",
    ),
    path("plan/", PayCyclePlanView.as_view(), name="solace-plan"),
    path("plan/checklist/", PayCycleChecklistView.as_view(), name="solace-plan-checklist"),
    path("bills/", BillListView.as_view(), name="solace-bill-list"),
    path("bills/<int:bill_id>/", BillDetailView.as_view(), name="solace-bill-detail"),
    path(
        "bills/<int:bill_id>/occurrences/",
        BillOccurrenceTimelineView.as_view(),
        name="solace-bill-occurrences",
    ),
    path("bills/<int:bill_id>/paid/", BillPaidView.as_view(), name="solace-bill-paid"),
    path("paydays/", PaydayListView.as_view(), name="solace-payday-list"),
    path("paydays/<int:payday_id>/", PaydayDetailView.as_view(), name="solace-payday-detail"),
    path("purchases/", PurchaseListView.as_view(), name="solace-purchase-list"),
    path("purchases/<int:purchase_id>/", PurchaseDetailView.as_view(), name="solace-purchase-detail"),
    path("purchases/<int:purchase_id>/add-saved/", PurchaseSavingsView.as_view(), name="solace-purchase-add-saved"),
    path("buckets/", BucketListView.as_view(), name="solace-bucket-list"),
    path("buckets/<int:bucket_id>/", BucketDetailView.as_view(), name="solace-bucket-detail"),
    path("subscriptions/", SubscriptionListView.as_view(), name="solace-subscription-list"),
    path("subscriptions/<int:subscription_id>/", SubscriptionDetailView.as_view(), name="solace-subscription-detail"),
    path("checklist/", ChecklistListView.as_view(), name="solace-checklist-list"),
    path("checklist/<int:item_id>/", ChecklistDetailView.as_view(), name="solace-checklist-detail"),
    path("checklist/preferences/", ChecklistPreferenceView.as_view(), name="solace-checklist-preferences"),
    path("categories/", FinanceCategoryListView.as_view(), name="solace-category-list"),
    path("categories/<int:category_id>/", FinanceCategoryDetailView.as_view(), name="solace-category-detail"),
    path("balances/", AccountBalanceListView.as_view(), name="solace-balance-list"),
    path("balances/<int:balance_id>/", AccountBalanceDetailView.as_view(), name="solace-balance-detail"),
]
