# Generated by Django 5.0.6 on 2026-06-25 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_household'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('icon', models.CharField(blank=True, default='🏅', max_length=20)),
                ('source', models.CharField(blank=True, default='', help_text="Node key that defines this badge, e.g. 'meridian'.", max_length=40)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'badge',
                'ordering': ['source', 'position', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AchievementCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(db_index=True, max_length=80)),
                ('value', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_counters', to='people.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'achievement counter',
                'ordering': ['person_id', 'key'],
            },
        ),
        migrations.CreateModel(
            name='PersonBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, default='', max_length=40)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='achievements.badge')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='people.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'person badge',
                'ordering': ['-earned_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='achievementcounter',
            constraint=models.UniqueConstraint(fields=('person', 'key'), name='unique_person_counter'),
        ),
        migrations.AddConstraint(
            model_name='personbadge',
            constraint=models.UniqueConstraint(fields=('person', 'badge'), name='unique_person_badge'),
        ),
    ]
