# Generated by Django 5.0.6 on 2026-08-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='book',
            name='source_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
