# Generated by Django 6.0.6 on 2026-06-24 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_household'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('is_core', models.BooleanField(default=False)),
                ('is_enabled_by_default', models.BooleanField(default=False)),
                ('requires_setup', models.BooleanField(default=False)),
                ('supports_kiosk', models.BooleanField(default=True)),
                ('supports_sensitive_lock', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('requires_reauthentication', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('custom_name', models.CharField(blank=True, default='', max_length=100)),
                ('custom_icon', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_nodes', to='core.household')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_configs', to='nodes.node')),
            ],
            options={
                'ordering': ['display_order', 'node__key'],
                'unique_together': {('household', 'node')},
            },
        ),
        migrations.CreateModel(
            name='NodeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value_json', models.JSONField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_settings', to='core.household')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='nodes.node')),
            ],
            options={
                'unique_together': {('household', 'node', 'key')},
            },
        ),
    ]
