# Generated by Django 5.0.6 on 2026-08-11 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelidea',
            name='hidden_from_users',
            field=models.ManyToManyField(blank=True, related_name='hidden_travel_ideas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='hidden_from_users',
            field=models.ManyToManyField(blank=True, related_name='hidden_trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
