# Generated by Django 6.0.6 on 2026-07-14 09:06

import apps.scheduling.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_household'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('teacher', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('colour', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_archived', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('household', 'Household'), ('role_restricted', 'Role Restricted'), ('sensitive', 'Sensitive')], default='household', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_courses', to='people.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'education course',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EducationClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('recurrence_rule', models.CharField(blank=True, default='', max_length=512)),
                ('calendar_event_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('household', 'Household'), ('role_restricted', 'Role Restricted'), ('sensitive', 'Sensitive')], default='household', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_class_sessions', to='people.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_sessions', to='education.educationcourse')),
            ],
            options={
                'verbose_name': 'education class session',
                'ordering': ['start_at'],
            },
            bases=(apps.scheduling.mixins.CalendarSyncMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EducationAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('assessment_type', models.CharField(choices=[('homework', 'Homework'), ('assignment', 'Assignment'), ('exam', 'Exam'), ('quiz', 'Quiz'), ('reading', 'Reading'), ('project', 'Project'), ('other', 'Other')], default='assignment', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('done', 'Done')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('weight', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('calendar_event_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('household', 'Household'), ('role_restricted', 'Role Restricted'), ('sensitive', 'Sensitive')], default='household', max_length=20)),
                ('sensitivity', models.CharField(choices=[('normal', 'Normal'), ('financial', 'Financial'), ('health', 'Health'), ('document', 'Document'), ('private', 'Private')], default='normal', max_length=20)),
                ('assigned_to_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_assessments', to='people.person')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='education.educationcourse')),
            ],
            options={
                'verbose_name': 'education assessment',
                'ordering': ['due_at', '-updated_at'],
            },
            bases=(apps.scheduling.mixins.CalendarSyncMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EducationInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('institution_type', models.CharField(choices=[('school', 'School'), ('university', 'University'), ('tafe', 'TAFE'), ('other', 'Other')], default='university', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('household', 'Household'), ('role_restricted', 'Role Restricted'), ('sensitive', 'Sensitive')], default='household', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'education institution',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='educationcourse',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='education.educationinstitution'),
        ),
    ]
