# Generated by Django 6.0.6 on 2026-07-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationassessment',
            name='is_all_day',
            field=models.BooleanField(default=False),
        ),
    ]
