# Generated by Django 6.0.7 on 2026-07-17 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_household_family_colour'),
        ('education', '0003_add_assessment_notes_files'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcourse',
            name='credit_value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educationcourse',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EducationAcademicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('programme_name', models.CharField(blank=True, default='', max_length=255)),
                ('credits_required', models.PositiveSmallIntegerField(default=0)),
                ('credits_per_course_default', models.PositiveSmallIntegerField(default=6)),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_profiles', to='education.educationinstitution')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education_profile', to='people.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'education academic profile',
                'ordering': ['person__display_name'],
            },
        ),
    ]
