# Generated by Django 5.0.6 on 2026-08-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_multi_person_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationclasssession',
            name='series_key',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
