# Generated by Django 6.0.6 on 2026-07-20 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_household_calendar_default_view_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('colour', models.CharField(blank=True, default='', max_length=20)),
                ('icon', models.CharField(blank=True, default='', max_length=40)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wiki category',
                'verbose_name_plural': 'wiki categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('tags', models.CharField(blank=True, default='', help_text='Comma-separated tags; exposed as a list in the API.', max_length=500)),
                ('is_favourite', models.BooleanField(default=False)),
                ('is_emergency', models.BooleanField(default=False)),
                ('is_kiosk_safe', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('household', 'Household'), ('role_restricted', 'Role Restricted'), ('sensitive', 'Sensitive')], default='household', max_length=20)),
                ('sensitivity', models.CharField(choices=[('normal', 'Normal'), ('sensitive', 'Sensitive')], default='normal', max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='home_wiki.wikicategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wiki page',
                'ordering': ['-is_favourite', 'title'],
            },
        ),
    ]
