# Generated by Django 5.0.6 on 2026-08-11 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_household_calendar_default_view_and_more'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CornerReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('activity_key', models.CharField(db_index=True, max_length=255)),
                ('emoji', models.CharField(max_length=16)),
                ('activity_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corner_activity_reactions_received', to='people.person')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('reactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corner_activity_reactions_made', to='people.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cornerreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('household', 'activity_key', 'reactor', 'emoji'), name='people_unique_corner_reaction'),
        ),
    ]
