# Generated by Django 6.0.6 on 2026-06-24 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_household'),
        ('nodes', '0002_seed_nodes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HubWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('supports_kiosk', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('source_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_widgets', to='nodes.node')),
            ],
            options={
                'ordering': ['display_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdHubWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_widgets', to='core.household')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.hubwidget')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('household', 'widget')},
            },
        ),
        migrations.CreateModel(
            name='UserHubWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_widgets', to=settings.AUTH_USER_MODEL)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.hubwidget')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('user', 'widget')},
            },
        ),
    ]
