# Generated by Django 5.0.6 on 2026-08-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_multi_person_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='event_kind',
            field=models.CharField(choices=[('event', 'Event'), ('appointment', 'Appointment'), ('birthday', 'Birthday'), ('holiday', 'Holiday'), ('task', 'Task / deadline')], default='event', max_length=16),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
