# Generated by Django 5.0.6 on 2026-08-11 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_calendarevent_contact_calendarevent_event_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='hidden_from_users',
            field=models.ManyToManyField(blank=True, help_text='Users explicitly excluded from surprise shared events.', related_name='hidden_calendar_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
