# Generated by Django 5.0.6 on 2026-08-17 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_calendar_sources'),
        ('scheduling', '0005_calendarevent_hidden_from_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='external_sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='external_uid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='is_range',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='last_seen_revision',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CalendarSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('holidays', 'Public holidays'), ('school', 'School calendar'), ('subscription', 'Subscribed calendar'), ('import', 'Imported calendar')], max_length=20)),
                ('provider', models.CharField(max_length=40)),
                ('is_enabled', models.BooleanField(default=True)),
                ('colour', models.CharField(blank=True, default='', max_length=7)),
                ('category', models.CharField(blank=True, default='', max_length=40)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('show_on_calendar', models.BooleanField(default=True)),
                ('show_in_upcoming', models.BooleanField(default=True)),
                ('notifications_enabled', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('idle', 'Never synced'), ('ok', 'Synced'), ('error', 'Failed')], default='idle', max_length=10)),
                ('sync_error', models.CharField(blank=True, default='', max_length=500)),
                ('sync_revision', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'calendar source',
                'verbose_name_plural': 'calendar sources',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='calendar_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scheduling.calendarsource'),
        ),
    ]
