# Generated by Django 6.0.6 on 2026-07-20 09:05

import apps.scheduling.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_household_calendar_default_view_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('fish', 'Fish'), ('reptile', 'Reptile'), ('small_mammal', 'Small mammal'), ('other', 'Other')], default='other', max_length=20)),
                ('breed', models.CharField(blank=True, default='', max_length=120)),
                ('avatar', models.CharField(blank=True, default='', max_length=255)),
                ('colour', models.CharField(blank=True, default='', max_length=40)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('adoption_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('vet_name', models.CharField(blank=True, default='', max_length=255)),
                ('vet_phone', models.CharField(blank=True, default='', max_length=50)),
                ('microchip_number', models.CharField(blank=True, default='', max_length=50)),
                ('insurance_provider', models.CharField(blank=True, default='', max_length=255)),
                ('insurance_policy_number', models.CharField(blank=True, default='', max_length=100)),
                ('food_notes', models.TextField(blank=True, default='')),
                ('is_archived', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('household', 'Household'), ('role_restricted', 'Role Restricted'), ('sensitive', 'Sensitive')], default='household', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pet',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PetAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('provider', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('calendar_event_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('household', 'Household'), ('role_restricted', 'Role Restricted'), ('sensitive', 'Sensitive')], default='household', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pets.pet')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pet appointment',
                'ordering': ['start_at'],
            },
            bases=(apps.scheduling.mixins.CalendarSyncMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PetTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('treatment_type', models.CharField(choices=[('flea', 'Flea'), ('worming', 'Worming'), ('vaccination', 'Vaccination'), ('medication', 'Medication'), ('grooming', 'Grooming'), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('last_done_at', models.DateTimeField(blank=True, null=True)),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
                ('recurrence_rule', models.CharField(blank=True, default='', max_length=512)),
                ('notes', models.TextField(blank=True, default='')),
                ('calendar_event_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('household', 'Household'), ('role_restricted', 'Role Restricted'), ('sensitive', 'Sensitive')], default='household', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='pets.pet')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pet treatment',
                'ordering': ['next_due_at', '-updated_at'],
            },
            bases=(apps.scheduling.mixins.CalendarSyncMixin, models.Model),
        ),
    ]
