# Generated by Django 6.0.6 on 2026-07-20 20:33

import apps.scheduling.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_household_calendar_default_view_and_more'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('appliance', 'Appliance'), ('heating', 'Heating / boiler'), ('kitchen', 'Kitchen'), ('laundry', 'Laundry'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('security', 'Security'), ('outdoor', 'Outdoor / garden'), ('other', 'Other')], default='appliance', max_length=20)),
                ('brand', models.CharField(blank=True, default='', max_length=160)),
                ('model_number', models.CharField(blank=True, default='', max_length=160)),
                ('serial_number', models.CharField(blank=True, default='', max_length=160)),
                ('room', models.CharField(blank=True, default='', max_length=120)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expires_at', models.DateField(blank=True, null=True)),
                ('warranty_provider', models.CharField(blank=True, default='', max_length=200)),
                ('manual_url', models.CharField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('household', 'Household'), ('role_restricted', 'Role Restricted'), ('sensitive', 'Sensitive')], default='household', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'appliance',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Improvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('planned', 'Planned'), ('in_progress', 'In progress'), ('on_hold', 'On hold'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='idea', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('room', models.CharField(blank=True, default='', max_length=120)),
                ('target_date', models.DateTimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=True)),
                ('project_ref', models.PositiveBigIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('calendar_event_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('household', 'Household'), ('role_restricted', 'Role Restricted'), ('sensitive', 'Sensitive')], default='household', max_length=20)),
                ('assigned_to_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.person')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'improvement',
                'ordering': ['-updated_at'],
            },
            bases=(apps.scheduling.mixins.CalendarSyncMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='Home', max_length=160)),
                ('address', models.TextField(blank=True, default='')),
                ('property_type', models.CharField(choices=[('house', 'House'), ('flat', 'Flat / apartment'), ('bungalow', 'Bungalow'), ('maisonette', 'Maisonette'), ('other', 'Other')], default='house', max_length=20)),
                ('tenure', models.CharField(choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold'), ('share_of_freehold', 'Share of freehold'), ('rented', 'Rented'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('year_built', models.CharField(blank=True, default='', max_length=20)),
                ('is_primary', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('water_shutoff', models.CharField(blank=True, default='', max_length=255)),
                ('gas_shutoff', models.CharField(blank=True, default='', max_length=255)),
                ('electricity_consumer_unit', models.CharField(blank=True, default='', max_length=255)),
                ('boiler_location', models.CharField(blank=True, default='', max_length=255)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('household', 'Household'), ('role_restricted', 'Role Restricted'), ('sensitive', 'Sensitive')], default='household', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('trade', models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('gas_engineer', 'Gas / heating engineer'), ('builder', 'Builder'), ('gardener', 'Gardener'), ('cleaner', 'Cleaner'), ('roofer', 'Roofer'), ('pest_control', 'Pest control'), ('handyman', 'Handyman'), ('other', 'Other')], default='other', max_length=20)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('last_used_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('household', 'Household'), ('role_restricted', 'Role Restricted'), ('sensitive', 'Sensitive')], default='household', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'service provider',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('heating', 'Heating'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('safety', 'Safety'), ('garden', 'Garden / outdoor'), ('exterior', 'Exterior'), ('cleaning', 'Cleaning'), ('appliance', 'Appliance'), ('renewal', 'Renewal / admin'), ('general', 'General')], default='general', max_length=20)),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=True)),
                ('recurrence_rule', models.CharField(blank=True, default='', max_length=512)),
                ('last_done_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('calendar_event_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('household', 'Household'), ('role_restricted', 'Role Restricted'), ('sensitive', 'Sensitive')], default='household', max_length=20)),
                ('appliance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to='homestead.appliance')),
                ('assigned_to_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.person')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='homestead.serviceprovider')),
            ],
            options={
                'verbose_name': 'maintenance task',
                'ordering': ['next_due_at', '-updated_at'],
            },
            bases=(apps.scheduling.mixins.CalendarSyncMixin, models.Model),
        ),
    ]
