# Generated by Django 6.0.6 on 2026-07-28 02:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_household_calendar_default_view_and_more'),
        ('homestead', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('cost_type', models.CharField(choices=[('rates', 'Council rates'), ('water', 'Water'), ('gas', 'Gas'), ('electricity', 'Electricity'), ('mortgage', 'Mortgage / rent'), ('body_corporate', 'Body corporate / strata'), ('waste', 'Waste'), ('internet', 'Internet'), ('other', 'Other')], default='other', max_length=30)),
                ('provider', models.CharField(blank=True, default='', max_length=200)),
                ('account_number', models.CharField(blank=True, default='', max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Every 6 months'), ('yearly', 'Yearly'), ('variable', 'Variable / usage based'), ('other', 'Other')], default='quarterly', max_length=20)),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
                ('recurrence_rule', models.CharField(blank=True, default='', max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('solace_bill_ref', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('household', 'Household'), ('role_restricted', 'Role Restricted'), ('sensitive', 'Sensitive')], default='sensitive', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'household cost',
                'ordering': ['next_due_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('policy_type', models.CharField(choices=[('building', 'Building'), ('contents', 'Contents'), ('building_contents', 'Building & contents'), ('landlord', 'Landlord'), ('mortgage_protection', 'Mortgage protection'), ('other', 'Other')], default='building_contents', max_length=30)),
                ('provider', models.CharField(blank=True, default='', max_length=200)),
                ('policy_number', models.CharField(blank=True, default='', max_length=160)),
                ('premium_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Every 6 months'), ('yearly', 'Yearly'), ('other', 'Other')], default='yearly', max_length=20)),
                ('next_renewal_at', models.DateTimeField(blank=True, null=True)),
                ('recurrence_rule', models.CharField(blank=True, default='', max_length=512)),
                ('standard_excess', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('additional_excesses', models.TextField(blank=True, default='')),
                ('coverage_summary', models.TextField(blank=True, default='')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('portal_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('solace_bill_ref', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('household', 'Household'), ('role_restricted', 'Role Restricted'), ('sensitive', 'Sensitive')], default='sensitive', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'insurance policy',
                'verbose_name_plural': 'insurance policies',
                'ordering': ['next_renewal_at', 'name'],
            },
        ),
    ]
