# Generated by Django 5.0.6 on 2026-08-10 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_household_calendar_default_view_and_more'),
        ('homestead', '0007_room_plan_project_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetask',
            name='category',
            field=models.CharField(choices=[('heating', 'Heating'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('safety', 'Safety'), ('garden', 'Garden / outdoor'), ('exterior', 'Exterior'), ('cleaning', 'Cleaning'), ('appliance', 'Appliance'), ('pool', 'Pool / spa'), ('renewal', 'Renewal / admin'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='Pool', max_length=160)),
                ('kind', models.CharField(choices=[('pool', 'Swimming pool'), ('spa', 'Spa / hot tub'), ('swim_spa', 'Swim spa'), ('plunge', 'Plunge pool')], default='pool', max_length=20)),
                ('sanitiser', models.CharField(choices=[('saltwater', 'Saltwater (chlorinator)'), ('chlorine', 'Manually chlorinated'), ('mineral', 'Mineral / magnesium'), ('bromine', 'Bromine'), ('other', 'Other')], default='saltwater', max_length=20)),
                ('surface', models.CharField(choices=[('concrete', 'Concrete / rendered'), ('fibreglass', 'Fibreglass'), ('vinyl_liner', 'Vinyl liner'), ('tiled', 'Fully tiled'), ('other', 'Other')], default='concrete', max_length=20)),
                ('filter_type', models.CharField(choices=[('sand', 'Sand'), ('cartridge', 'Cartridge'), ('glass', 'Glass media'), ('de', 'Diatomaceous earth'), ('other', 'Other')], default='other', max_length=20)),
                ('volume_litres', models.PositiveIntegerField(blank=True, null=True)),
                ('is_indoor', models.BooleanField(default=False)),
                ('equipment_notes', models.TextField(blank=True, default='', help_text='Pump, filter and chlorinator models, settings, quirks.')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('household', 'Household'), ('role_restricted', 'Role Restricted'), ('sensitive', 'Sensitive')], default='household', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pools', to='homestead.roomarea')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pool or spa',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_tasks', to='homestead.pool'),
        ),
        migrations.CreateModel(
            name='WaterTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tested_at', models.DateTimeField()),
                ('free_chlorine', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('total_alkalinity', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('calcium_hardness', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('cyanuric_acid', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('salt', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('water_temp_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_tests', to='homestead.pool')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'water test',
                'ordering': ['-tested_at', '-id'],
            },
        ),
    ]
