# Generated by Django 6.0.6 on 2026-08-10 05:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_household_calendar_default_view_and_more'),
        ('homestead', '0008_pool_and_water_tests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('utility_type', models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water'), ('gas', 'Gas'), ('other', 'Other')], default='electricity', max_length=20)),
                ('provider', models.CharField(blank=True, default='', max_length=200)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('usage_amount', models.DecimalField(decimal_places=3, help_text='How much was used over the period, in `usage_unit`.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('usage_unit', models.CharField(choices=[('kwh', 'kWh'), ('kl', 'kL'), ('litres', 'L'), ('m3', 'm³'), ('mj', 'MJ'), ('therms', 'therms'), ('other', 'units')], default='kwh', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total charged for the period, including supply charges.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_estimated', models.BooleanField(default=False, help_text='The meter was estimated rather than read.')),
                ('notes', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('household', 'Household'), ('role_restricted', 'Role Restricted'), ('sensitive', 'Sensitive')], default='household', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.household')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'utility bill',
                'ordering': ['-period_end', '-id'],
                'indexes': [models.Index(fields=['utility_type', 'period_end'], name='homestead_u_utility_b4863a_idx')],
            },
        ),
    ]
