# Generated by Django 5.0.6 on 2026-08-11 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
        ('homestead', '0010_solace_owns_home_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomplanproduct',
            name='currency',
            field=models.CharField(blank=True, default='AUD', max_length=3),
        ),
        migrations.AddField(
            model_name='roomplanproduct',
            name='image_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homestead_room_products', to='attachments.attachment'),
        ),
        migrations.AddField(
            model_name='roomplanproduct',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomplanproduct',
            name='source_image_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
